services:
  - type: web
    name: faresphere-mominur
    runtime: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/v1/health
    autoDeployTrigger: checksPass
    envVars:
      - key: ENABLE_SAMPLE_DATA
        value: "false"
